### ISSUE TITLE
hi ... i've got Error on $php artisan voyager-pages:install

### ISSUE THREAD

**Issue by ElectroArmy** [pvtl/voyager-pages#2]
$ php artisan voyager-pages:install

Publishing Pages assets, database, and config files
Publishing complete.
Dumping the autoloaded files and reloading all new files
Migrating the database tables into your application
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2016_01_01_000000_add_voyager_user_fields
Migrated:  2016_01_01_000000_add_voyager_user_fields
Migrating: 2016_01_01_000000_create_data_types_table
Migrated:  2016_01_01_000000_create_data_types_table
Migrating: 2016_05_19_173453_create_menu_table
Migrated:  2016_05_19_173453_create_menu_table
Migrating: 2016_10_21_190000_create_roles_table
Migrated:  2016_10_21_190000_create_roles_table
Migrating: 2016_10_21_190000_create_settings_table
Migrated:  2016_10_21_190000_create_settings_table
Migrating: 2016_11_30_135954_create_permission_table
Migrated:  2016_11_30_135954_create_permission_table
Migrating: 2016_11_30_141208_create_permission_role_table
Migrated:  2016_11_30_141208_create_permission_role_table
Migrating: 2016_12_26_201236_data_types__add__server_side
Migrated:  2016_12_26_201236_data_types__add__server_side
Migrating: 2017_01_13_000000_add_route_to_menu_items_table
Migrated:  2017_01_13_000000_add_route_to_menu_items_table
Migrating: 2017_01_14_005015_create_translations_table
Migrated:  2017_01_14_005015_create_translations_table
Migrating: 2017_01_15_000000_make_table_name_nullable_in_permissions_table
Migrated:  2017_01_15_000000_make_table_name_nullable_in_permissions_table
Migrating: 2017_03_06_000000_add_controller_to_data_types_table
Migrated:  2017_03_06_000000_add_controller_to_data_types_table
Migrating: 2017_04_21_000000_add_order_to_data_rows_table
Migrated:  2017_04_21_000000_add_order_to_data_rows_table
Migrating: 2017_07_05_210000_add_policyname_to_data_types_table
Migrated:  2017_07_05_210000_add_policyname_to_data_types_table
Migrating: 2017_08_05_000000_add_group_to_settings_table
Migrated:  2017_08_05_000000_add_group_to_settings_table
Migrating: 2017_11_26_013050_add_user_role_relationship
Migrated:  2017_11_26_013050_add_user_role_relationship
Migrating: 2017_11_26_015000_create_user_roles_table
Migrated:  2017_11_26_015000_create_user_roles_table
Migrating: 2018_03_11_000000_add_user_settings
Migrated:  2018_03_11_000000_add_user_settings
Migrating: 2018_03_14_000000_add_details_to_data_types_table
Migrated:  2018_03_14_000000_add_details_to_data_types_table
Migrating: 2018_03_16_000000_make_settings_value_nullable
Migrated:  2018_03_16_000000_make_settings_value_nullable
Migrating: 2018_04_18_000000_create_pages_table
Migrated:  2018_04_18_000000_create_pages_table
Seeding data into the database

   Illuminate\Database\Eloquent\ModelNotFoundException  : No query results for model [TCG\Voyager\Models\Menu].

  at C:\xampp\htdocs\laravelapp\Voyagerpages\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Builder.php:414
    410|         if (! is_null($model = $this->first($columns))) {
    411|             return $model;
    412|         }
    413|
  > 414|         throw (new ModelNotFoundException)->setModel(get_class($this->model));
    415|     }
    416|
    417|     /**
    418|      * Execute the query and get the first result or call a callback.

  Exception trace:

  1   Illuminate\Database\Eloquent\Builder::firstOrFail()
      C:\xampp\htdocs\laravelapp\Voyagerpages\vendor\pvtl\voyager-pages\database\seeds\PagesMenuItemsTableSeeder.php:19

  2   PagesMenuItemsTableSeeder::run()
      C:\xampp\htdocs\laravelapp\Voyagerpages\vendor\tcg\voyager\src\Traits\Seedable.php:13

  Please use the argument -v to see more details.

**Comment by ElectroArmy** [comment]
voyager-pages:install Error :(
$ php artisan voyager-pages:install
Publishing Pages assets, database, and config files
Publishing complete.
Dumping the autoloaded files and reloading all new files
Migrating the database tables into your application
Nothing to migrate.
Seeding data into the database

   Symfony\Component\Debug\Exception\FatalThrowableError  : Class 'AlgoliaSearch
\Version' not found

  at C:\xampp\htdocs\laravelapp\voyagerfullstack\vendor\laravel\scout\src\Engine
Manager.php:31
    27|      * @return \Laravel\Scout\Engines\AlgoliaEngine
    28|      */
    29|     public function createAlgoliaDriver()
    30|     {
  > 31|         AlgoliaUserAgent::addSuffixUserAgentSegment('Laravel Scout', '3.
0.10');
    32|
    33|         return new AlgoliaEngine(new Algolia(
    34|             config('scout.algolia.id'), config('scout.algolia.secret')
    35|         ));

  Exception trace:

  1   Laravel\Scout\EngineManager::createAlgoliaDriver()
      C:\xampp\htdocs\laravelapp\voyagerfullstack\vendor\laravel\framework\src\I
lluminate\Support\Manager.php:94

  2   Illuminate\Support\Manager::createDriver("algolia")
      C:\xampp\htdocs\laravelapp\voyagerfullstack\vendor\laravel\framework\src\I
lluminate\Support\Manager.php:69

  Please use the argument -v to see more details.

**Comment by lukewmoore** [comment]
Hi @ElectroArmy 

If you're using voyager-frontend you'll also need to add `SCOUT_DRIVER=tntsearch` to your .env before running `php artisan voyager-frontend:install`

**Comment by ElectroArmy** [comment]
thanks Bro :D
