### ISSUE TITLE
Cannot declare class CreatePagesTable

### ISSUE THREAD

**Issue by jnijland** [pvtl/voyager-pages#5]
When trying to migrate, I receive the following error: 

```
Whoops\Exception\ErrorException  : Cannot declare class CreatePagesTable, because the name is already in use at {path}/vendor/pvtl/voyager/pages/database/migrations/2018_04_18_000000_create_pages_table.php:42
```

It is a fresh installation.

**Comment by mcnamee** [comment]
Hi @jnijland 
Did you install Voyager with `php artisan voyager:install --with-dummy`? If so, the `--with-dummy` flag has already added a 'Pages' to the DB - meaning you already had pages (likely no need for this module).
