### ISSUE TITLE
Not compatible with new version of Voyager

### ISSUE THREAD

**Issue by KonradMil** [pvtl/voyager-pages#6]
https://github.com/the-control-group/voyager/pull/3836

broke the code in here: 

```
PHP Fatal error:  Trait 'TCG\Voyager\Traits\HasRelationships' not found in /var/www/kpcn/vendor/pvtl/voyager-pages/src/Page.php on line 12

In Page.php line 12:
                                                         
  Trait 'TCG\Voyager\Traits\HasRelationships' not found  
```

**Comment by axelex** [comment]
I confirm that this is indeed an issue:

composer require pvtl/voyager-pages
Using version ^0.2.7 for pvtl/voyager-pages
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing pvtl/voyager-pages (0.2.7): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Trait 'TCG\Voyager\Traits\HasRelationships' not found in /var/www/mo_sanyi/vendor/pvtl/voyager-pages/src/Page.php on line 12

In Page.php line 12:
                                                         
  Trait 'TCG\Voyager\Traits\HasRelationships' not found  
                                                         

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 255

**Comment by Nks** [comment]
Any update?

**Comment by mcnamee** [comment]
This has been resolved in the latest release
