### ISSUE TITLE
Why does this package exist?

### ISSUE THREAD

**Issue by LarryTX** [pvtl/voyager-pages#8]
Pvtl seems to do the very same thing on all their packages. Simply throw their package on GitHub like so much slop and leave it to the user to figure out what it's for, why he would want to use it, how it improves what already exists, how to make it work, and on and on and on. Take this one for an example. I know what "pages" or "static pages" are in the common PHP and Laravel parlance.

- Does this package create the typical static web pages? (Some developers chose to use a term like "pages" with no regard to common usage. Do the "pages" referenced by this package vary from standard usage [HTML in a file with no database or table connection] or conform to it?)
- For the benefit of the less skilled user, what type of "pages" does this package create? How are they different from every other web page that are displayed through Laravel and Voyager? (Yes, you do need to explain the difference between the pages developed with this package and the dynamic pages more typical of Laravel and Voyager that derive from a database. Oh, but these pages rely on a database table! Now your user is totally confused.)
- If this package creates "pages" that conform to the standard terminology, why on earth would I want to use this package to do something that I can already do within Laravel and Voyager? How does it improve on the existing abilities to create such pages? Given that these pages are "stored" in a database table, why is that better than just creating a typical, static HTML page, even if it's created with Blade.
- By the by, you have a meta_description field in your database table. I like to have more meta tags with attributes like, title, robots, google, the good old http-equiv's, and I wouldn't remove keywords. But then,I tend to roll up all the meta's into a JSON field in the table. Keeps everything together and gives me more flexibility. Can I do that with your package? Where in your instructions can I find out about that?
- Speaking of tables, in your table you define a status enum column that calls Page::$statuses for its definition. So as a very frustrated new user, can I just add a new status, like Published (because I have some pages in a Draft status before they're published), to the Statuses in the Model (Page.php) and expect to be able to use the new Status on my pages? (No!) What do I need to do to make this package work with Statuses like Draft, Published, InDevelopment? Where do I find that in your instructions? You don't have those kind of instructions!#@%%%!!! Time to run to a better framework! Here I come WordPress/Yii2/etc.! Ditch Laravel, Voyager, and the whole rotten bunch!

Developers of add-ons/add-ins/packages/modules/whatever are the ultimate salesmen for a framework like Laravel. This callous disregard of users, expecting them to dig around in source code to find out if a package like this even fits their use cases, does nothing but drive users away from a framework like Laravel and a package like Voyager. Is this what you actually want to do?

By the way, the complete and total paucity of installation instructions coupled with a complete and total lack of usage instructions also does nothing but drive users totally fleeing to frameworks like Wordpress, Yii2, and a myriad of others that have vastly better documentation for such add-ons (using a more generic term, rather than the Laravel specific packages). I note that the Laravel documentation, itself, found at [https://laravel.com/docs/5.7](https://laravel.com/docs/5.7), is so vastly, immensely greater than that "provided" (slung out there) by Pivotal Agency that Pivotal should be totally embarrassed by it. You really should take a little bit of time to actually read the Laravel documentation and emulate it. If it had been like your documentation could you ever have done as much with Laravel as you have?

Come on folks, we all want Laravel and Voyager to succeed. Don't be an impediment, no don't be a total blockade to having that success happen! And along the way, lessen the user frustration trying to make your packages work. Oh and also improve the professionalism of your products.

**Comment by mcnamee** [comment]
As the readme states - this package adds a **Pages** content type to the [Voyager](https://github.com/the-control-group/voyager) admin area.

We've open sourced this package as we use it internally + it's a dependency for [another project](https://github.com/pvtl/voyager-frontend).

All the best @LarryTX ❤
